swagger: "2.0"
info:
  title: "DiagramAsText API"
  description: |
    API to generate diagrams using the <a href="https://diagramastext.dev" target="_blanck">diagramastext.dev</a> core logic.
  version: "0.0.6"
  contact:
    email: contact@diagramastext.dec
    name: in case of questions
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: api.diagramastext.dev
basePath: /
schemes:
  - https
security:
  - Authorization: []
paths:
  /generate/c4:
    post:
      tags:
        - "Generate diagram using plain English"
      summary: "Generates C4 Containers diagram"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Input prompt in plain English"
          required: true
          schema:
            $ref: "#/definitions/RequestGenerateDiagram"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/ResponseDaigramSVG"
        '400':
          description: Invalid request format
          schema:
            $ref: "#/definitions/Error"
        '401':
          description: Unauthorized
          schema:
            $ref: "#/definitions/Error"
        '422':
          description: Invalid input prompt
          schema:
            $ref: "#/definitions/Error"
        '429':
          description: Throttling quota exceeded
          schema:
            $ref: "#/definitions/Error"
        '500':
          description: Core logic error
          schema:
            $ref: "#/definitions/Error"
securityDefinitions:
  Authorization:
    type: "apiKey"
    name: "Authorization"
    in: "header"
    description: "API access key"
definitions:
  RequestGenerateDiagram:
    type: object
    required:
      - "prompt"
    additionalProperties: false
    properties:
      prompt:
        description: "Diagram description in plain English"
        type: "string"
        minLength: 3
  ResponseDaigramSVG:
    type: object
    required:
      - "svg"
    additionalProperties: false
    properties:
      svg:
        description: "Generated diagram as SVG"
        type: "string"
  Error:
    type: object
    required:
      - "error"
    additionalProperties: false
    properties:
      error:
        description: "Error message"
        type: "string"
        minLength: 1
