version: '3'
services:
  server:
    image: golang:1.19.3-alpine3.17
    container_name: diagranastext-core
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      CORS_HEADERS: '{"Access-Control-Allow-Origin":"http://localhost:${PORT_CLIENT}","Access-Control-Allow-Methods":"POST,OPTIONS","Access-Control-Allow-Headers":"Content-Type,X-Amz-Date,x-api-key,Authorization,X-Api-Key,X-Amz-Security-Token"}'
      PORT: 9000
    ports:
      - ${PORT_SERVER}:9000
    volumes:
      - ./server/core:/app
    working_dir: /app
    command: ["/bin/sh", "-c", "go mod tidy && go run cmd/httpserver/main.go"]

  webclient:
    image: golang:1.19.3-alpine3.17
    container_name: diagranastext-webclient
    environment:
      API_URL: "http://localhost:${PORT_SERVER}/"
      VERSION: $VERSION
      TOKEN: 'foobar'
    ports:
      - ${PORT_CLIENT}:8080
    volumes:
      - ./webclient:/public
    working_dir: /public
    command: [ "/bin/sh", "-c", "go run main.go", "--port", "8080", "--path", "/public" ]
