name: "Deploy:Server"

on:
  pull_request:
    paths:
      - "server/core/**"
      - "!server/core/**.md"
      - "!server/core/fig/**"
      - "!server/core/Makefile"
  push:
    branches:
      - master
    paths:
      - "server/core/**"
      - "!server/core/**.md"
      - "!server/core/fig/**"
      - "!server/core/Makefile"

  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  pull-requests: write

jobs:
  list_modules:
    defaults:
      run:
        working-directory: "server/core"
    runs-on: ubuntu-latest
    name: "List modules"
    outputs:
      modules: ${{ steps.ls.outputs.modules }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: ls
        id: ls
        run: echo "modules=$(python3 ../../.github/workflows/scripts/ls_modules.py -p .)" >> $GITHUB_OUTPUT

  unittest:
    defaults:
      run:
        working-directory: "server/core"
    runs-on: ubuntu-latest
    name: "Unittest"
    needs:
      - list_modules
    strategy:
      matrix:
        module: ${{ fromJSON(needs.list_modules.outputs.modules) }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Unittests
        run: |
          cd ${{ matrix.module.path }}
          go mod tidy
          go test -race -coverprofile=${{ matrix.module.flag }}.txt -covermode=atomic ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: ${{ matrix.module.flag }}
          files: ${{ matrix.module.flag }}.txt

  lint:
    runs-on: ubuntu-latest
    name: "Lint"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: "server/core"

  test-infra:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs:
      - unittest
      - lint
    defaults:
      run:
        working-directory: "server/core/deployment"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::027889758114:role/GitHubActions-production
          role-duration-seconds: 900
      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2.0.3
      - name: Terraform init
        id: init
        run: terraform init
      - name: Terraform validate
        id: validate
        run: terraform validate
      - name: Terraform plan
        id: plan
        run: |
          terraform workspace select staging
          terraform plan -lock-timeout=120s -no-color -out /tmp/terraform.tfplan
        continue-on-error: true
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Prepare format of the comment
            const resultValidate = `${{ steps.validate.outputs.exitcode }}` === '0' ? `${{ steps.validate.outputs.stdout }}` : `${{ steps.validate.outputs.stderr }}`;
            const resultPlan = `${{ steps.plan.outputs.exitcode }}` === '0' ? `${{ steps.plan.outputs.stdout }}` : `${{ steps.plan.outputs.stderr }}`;
            
            const output = `#### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            <details><summary>Validation Output</summary>
            
            \`\`\`\n
            ${resultValidate}
            \`\`\`
            
            </details>
            
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            
            <details><summary>Show Plan</summary>
            
            \`\`\`\n
            ${resultPlan}
            \`\`\`
            
            </details>
            
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;
            
            // Publish comment
            github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
            })
      - name: Status check
        run: |
          if [[ ! ${{ steps.validate.outputs.exitcode }} -eq 0 ]]; then echo "failed validation"; exit 1; fi
          if [[ ! ${{ steps.plan.outputs.exitcode }} -eq 0 ]]; then echo "failed plan"; exit 1; fi

  deployment-staging:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    environment:
      name: "staging:server"
    needs:
      - unittest
      - lint
    defaults:
      run:
        working-directory: "server/core/deployment"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::027889758114:role/GitHubActions-production
          role-duration-seconds: 900
      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2.0.3
      - name: Terraform init
        id: init
        run: terraform init
      - name: Terraform validate
        id: validate
        run: terraform validate
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Deploy
        run: |
          terraform workspace select staging
          terraform plan -lock-timeout=120s
          terraform apply -auto-approve  

  deployment-production:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    environment:
      name: "production:server"
    needs:
      - deployment-staging
    defaults:
      run:
        working-directory: "server/core/deployment"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::027889758114:role/GitHubActions-production
          role-duration-seconds: 900
      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2.0.3
      - name: Terraform init
        id: init
        run: terraform init
      - name: Terraform validate
        id: validate
        run: terraform validate
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Deploy
        run: |
          terraform plan -lock-timeout=120s
          terraform apply -auto-approve  
