name: "Deploy:Webclient"

on:
  push:
    branches:
      - master
    paths:
      - "webclient/**/*"
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment: production
    permissions:
      contents: write
    if: github.ref == 'refs/heads/master' || (github.event.pull_request.merged == 'true' && github.base_ref == 'master' )
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate webclient
        env:
          TOKEN: ${{ secrets.GW_API_TOKEN }}
        run: docker run -e TOKEN=$TOKEN -v ${PWD}:/app -t hairyhenderson/gomplate:stable -f /app/webclient/index.html -o /app/public/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
