name: "Lint:Core"

on:
  push:
  pull_request:
    paths:
      - "core/**/*.go"
    branches:
      - master

jobs:
  link:
    runs-on: ubuntu-latest
    name: "Lint"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: core
