name: "Tests:Core"

on:
  push:
    paths:
      - "core/**/*.go"
      - "core/**/go.mod"
      - "core/**/go.sum"
  pull_request:
    branches:
      - master
    paths:
      - "core/**/*.go"
      - "core/**/go.mod"
      - "core/**/go.sum"

jobs:
  test:
    defaults:
      run:
        working-directory: "core"
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Unittests
        run: |
          go mod tidy
          go test -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: module
          files: coverage.txt

      - name: Unittests-lambda
        run: |
          cd cmd/lambda
          go mod tidy
          go test -race -coverprofile=coverage-lambda.txt -covermode=atomic

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: lambda
          files: coverage-lambda.txt

      - name: Unittests-storage/postgres
        run: |
          cd storage
          go mod tidy
          go test -race -coverprofile=coverage-postgres.txt -covermode=atomic

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: postgres
          files: coverage-postgres.txt
